name: Build & Deploy

on:
  push:
    branches:
      - main
      - python
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.9'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: Copy Model From Azure
        uses: ulaval/azure-blob-copy-action@v1
        with:
          action: download
          connection_string: ${{ secrets.STORAGE_CONNECTION_STRING }}
          container_name: model
          local_directory: ./predict/model

      - name: Deploy to Azure Function
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'mousemapp'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}